project:
  type: website
  output-dir: docs

website:
  favicon: imgs/carminemnc_w_500x500.webp
  google-analytics: 
    tracking-id: "G-BEX0MX4L1P"
    anonymize-ip: true
  site-url: https://carminemnc.github.io/
  search: true
  navbar: 
    logo: imgs/carminemnc_x_500x500.webp
    right:
      - href: posts.qmd
        text: Posts
      - href: projects.qmd
        text: Projects
      - href: notebooks.qmd
        text: Notebooks
      - href: resume/carmine_minichini_resume.pdf
        text: Resume
format:
  html:
    include-in-header: font-preload.html
    toc: true
    code-fold: true
    code-overflow: wrap
    code-block-border-left: true
    code-annotations: hover
    theme:
      light: light-theme.scss
      dark: dark-theme.scss
    mainfont: Noto Serif
    highlight-style: ayu-dark
    title-block-banner: false
    html-math-method: katex
    toc-title: Table of contents
    tbl-cap-location: bottom
    



